sudo: required
services: 
  - docker

before_install: 
  - docker build -t kavin1/react-test -f ./client/Dockerfile.dev ./client

scripts: 
  - docker run -e CI=true kavin1/react-test npm test

after_sucess:
  - docker build -t kavin1/multi-client ./client
  - docker build -t kavin1/multi-nginx ./nginx
  - docker build -t kavin1/multi-server ./server
  - docker build -t kavin1/multi-worker ./worker

  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the images and push them to docker hub
  - docker push kavin1/multi-client
  - docker push kavin1/multi-nginx
  - docker push kavin1/multi-server
  - docker push kavin1/multi-worker



deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'multi-docker-test'
  env: 'MultiDockerTest-env'
  bucket_name: "elasticbeanstalk-ap-southeast-1-964317254124"
  bucket_path: "multi-docker-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $SECRET_ACCESS_KEY